### ISSUE TITLE
 Expected object of scalar type Long but got scalar type Float for argument #2 'target'

### ISSUE THREAD

**Issue by MrJiggsaw** [hunkim/PyTorchZeroToAll#38]
I followed the concept given above ,
took the data,normalized ,split into train and test data and when training ,it says that it want type long but got float32 

Any help would be appreciated

**Comment by jianlianggao** [comment]
You can try to add Variable(<your tensor data>).long()

**Comment by MrJiggsaw** [comment]
I tried everything .It toggles between float and long
When I change the datatype to long it asks float and vice versa i.e. when float then expects long.


I found the solution by the way 
I just converted the nominal features into one_hot_encode and it worked
