### ISSUE TITLE
PyTorchDataParallel tutorial?

### ISSUE THREAD

**Issue by hunkim** [hunkim/PyTorchZeroToAll#9]
@chsasank, are you potentially interested in this kind of tutorial: https://github.com/hunkim/PyTorchZeroToAll/blob/master/tutorials/PyTorchDataParallel.ipynb

It seems current tutorial (http://pytorch.org/tutorials/beginner/former_torchies/parallelism_tutorial.html) does not have enough information/examples.

Cheers!

**Comment by chsasank** [comment]
Hey!

That'd certainly be useful. We can add this short tutorial to blitz as optional step.
With a few modifications to match the narrative style and a few things here and there this can be done.
What do you think?

Sasank.

cc: @soumith

PS: Sorry for late reply.

**Comment by hunkim** [comment]
@chsasank Wonderful! I'll polish more and rewrite it to the Sphinx format and send a PR in a few days. Then, you can give me lots of comments on the PR.

Cheers!

**Comment by chsasank** [comment]
You can use this script to convert your notebook: https://gist.github.com/chsasank/7218ca16f8d022e02a9c0deb94a310fe

See contributing in readme in https://github.com/pytorch/tutorials
